documentation:
- changed-files:
  - any-glob-to-any-file: ['doc/**/*', 'examples/**/*']
maintenance:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', '.flake8', '.codespellrc', 'pyproject.toml']
dependencies:
- changed-files:
  - any-glob-to-any-file: ['requirements/*']